version: '3.4'

services:
  beolinkaudioserver:
    container_name: beolinkaudioserver
    hostname: beolinkaudioserver
    image: beolinkaudioserver
    env_file:
        - .env.example
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 7091:7091
      - 7095:7095
